export const airportminimums = [
	{ front: "What are CAT I minimums?", back: "<b>HAT</b> - 200'<br><b>RVR</b> - 2400' or 1800 w/ Center Line Lights and Touchdown Zone Lines" },
	{ front: "What are CAT II (SA) minimums?", back: "<b>HAT</b> - 150'<br><b>RVR</b> - 1400'" },
	{ front: "What are CAT II minimums?", back: "<b>HAT</b> - 100'<br><b>RVR</b> - 1200'" },
	{ front: "What are CAT IIIA minimums?", back: "<b>HAT</b> - 100'<br><b>RVR</b> - 700'" },
	{ front: "What are CAT IIIB minimums?", back: "<b>HAT</b> - 50'<br><b>RVR</b> - 150'" },
	{ front: "What are CAT IIIC minimums?", back: "<b>HAT</b> - 0'<br><b>RVR</b> - 0'<br>(Not Authorized in USA)" },
	{ front: "What are Standard Takeoff Minimums", back: "With 2 Engines Operative - 1SM<br>With 3+ Engines Operative - ½SM<br>(FAR 121.617)" },
	{ front: "What do we use for Standard Takeoff Minimums?", back: "C-078 or JEPP-9A" },
	{ front: "Standard Alternate Minimums<br>Not in our Ops Spec", back: "Precision - 600-2<br>Non-Precision - 800-2" },
	{ front: "C-055 Alternate Minimums", back: "1 Approach - +400'-1<br>2 Approach - +200'-½" },
	{ front: "When is a Departure Alternate Required?", back: "When weather is below landing minimums at the departure airport" },
	{ front: "How far can a Departure Alternate be for a 2 engine aircraft?", back: "1 Hour, In Still Air, With 1 Engine Inoperative" },
	{ front: "How far can a Departure Alternate be for a 3+ engine aircraft?", back: "2 Hours, In Still Air, With 1 Engine Inoperative" },
	{ front : "When is a departure alternate required?", back: "When weather is below landing minimums at the departure<br>(FAR 121.617)" },
	{ front : "What are C-055 alternate minimums?", back: "1 Approach: +400'-1<br>2 Approach: +200'-½" },
	{ front : "What are standard alternate minimums?", back: "Precision: 600-2<br>Non-Precision: 800-2" },
	{ front : "What are standard takeoff minimums?", back: "2 Engine: 1SM<br>3+ Engine: ½SM" },
	{ front : "When is a drift down alternate required?", back: "When you cannot maintain method 1" },
	{ front : "When is a destination alternate required?", back: `It's required when + or - 1 hour the ETA, the TAF indicates less than... 2000' ceiling and/or 3SM of visibility<br>The "1-2-3" rule (FAR 121.619)` },
	{ front : "When is a second alternate required?", back: "When weather for the destination and first alternate are marginal<br>Marginal = 600-2" },
	{ front : "What is a High Minimum Captain?", back: "A captain with less than 100 hours in aircraft type" },
	{ front : "What minimums are affected by a High Minimum Captain?", back: "the Landing minimums" },
	{ front : "What is a Restricted Captain?", back: "CAT II Qualified, but not current" },
	{ front : "What must a Restricted Captain do to maintain currency?", back: "Must have 3 CAT II approaches every 6 months" },
	{ front : "What defines 2 different approaches?", back: "2 different runways (R9 & R27) Can be the same piece of pavement<br>2 different NAVAID ID's (IABC + IDEF)" },
	{ front : "Using C-055, with 1 NAVAID, what are your minimums for the following?<br>200'-½", back: "600'-1-½" },
	{ front : "Using C-055, with 1 NAVAID, what are your minimums for the following?<br>250'-½", back: "700'-1-½" },
	{ front : "Using C-055, with 2 NAVAIDs, what are your minimums for the following?<br>200'-½<br>250'-¾", back: "500'-1-¼" },
	{ front : "Using C-055, with 2 NAVAIDs, what are your minimums for the following?<br>200'-½<br>200'-½", back: "400'-1" },
	{ front : "Using C-055, with 2 NAVAIDs, what are your minimums for the following?<br>225'-½<br>200'-¾", back: "500'-1-¼" },
	{ front : "How do you apply C-055 alternate minimums using the 2 NAVAID rule?", back: "Based on your two plates you have chosen, you will add to the highest of the two plate minimums" },
	{ front : "What do you for a High Minimum Captain at the departure airport?", back: "Add 100'-½ (always RVR)" },
	{ front : "What do you for a High Minimum Captain at the destination airport?", back: "Add 100'-½ (always RVR)" },
	{ front : "What do you for a High Minimum Captain at an alternate airport?", back: "No less than 300'-1 (always RVR)" },
];
