export const airportminimums = [
  { front: "CAT I", back: "HAT - 200' RVR - 2400' or 1800 w/ Center Line Lights and Touchdown Zone Lines" },
  { front: "CAT II (SA)", back: "HAT - 150'<br>RVR - 1400'" },
  { front: "CAT II", back: "HAT - 100'<br>RVR - 1200'" },
  { front: "CAT IIIA", back: "HAT - 100'<br>RVR - 700'" },
  { front: "CAT IIIB", back: "HAT - 50'<br>RVR - 150'" },
  { front: "CAT IIIC", back: "HAT - 0'<br>RVR - 0'<br>(Not Authorized in USA)" },
  { front: "Origin<br>Standard Takeoff Minimums", back: "With 2 Engines Operative - 1SM<br>With 3+ Engines Operative - 1/2SM<br>(FAR 121.617)" },
  { front: "What do we use for Standard Takeoff Minimums?", back: "C-078 or JEPP-9A" },
  { front: "Standard Alternate Minimums<br>Not in our Ops Spec", back: "Precision - 600'-2SM<br>Non-Precision - 800'-2SM" },
  { front: "C-055 Alternate Minimums", back: "1 Approach - +400'-1SM<br>2 Approach - +200'-1/2SM(To the highest)" },
  { front: "When is a Depature Alternate Required?", back: "When weather is below landing minimums at the departure airport" },
  { front: "How Far Can a Depature Alternate be for a 2 Engine Aircraft?", back: "1 Hour, In Still Air, With 1 Engine Inoperative" },
  { front: "How Far Can a Depature Alternate be for a 3+ Engine Aircraft?", back: "2 Hours, In Still Air, With 1 Engine Inoperative" },
  { front: "PLACEHOLDER", back: "PLACEHOLDER" },
  { front: "PLACEHOLDER", back: "PLACEHOLDER" },
  { front: "PLACEHOLDER", back: "PLACEHOLDER" },
  { front: "PLACEHOLDER", back: "PLACEHOLDER" },
  { front: "PLACEHOLDER", back: "PLACEHOLDER" },
  { front: "PLACEHOLDER", back: "PLACEHOLDER" },
  { front: "PLACEHOLDER", back: "PLACEHOLDER" },
  { front: "PLACEHOLDER", back: "PLACEHOLDER" },
  { front: "PLACEHOLDER", back: "PLACEHOLDER" },
  { front: "PLACEHOLDER", back: "PLACEHOLDER" },
  { front: "PLACEHOLDER", back: "PLACEHOLDER" },
  { front: "PLACEHOLDER", back: "PLACEHOLDER" },
  { front: "PLACEHOLDER", back: "PLACEHOLDER" },
  { front: "PLACEHOLDER", back: "PLACEHOLDER" },
  { front: "PLACEHOLDER", back: "PLACEHOLDER" },
  { front: "PLACEHOLDER", back: "PLACEHOLDER" },
  { front: "PLACEHOLDER", back: "PLACEHOLDER" }
];
