//* flightlevels
export const flightlevels = [
      { front : `What is the top of Class A airspace?`, back: `FL600` },
      { front : `What is the top of the High Altitude Chart?`, back: `FL450` },
      { front : `What is the top of RVSM airspace?`, back: `FL410` },
      { front : `What is the service ceiling for a B737-800?`, back: `FL410` },
      { front : `What is the bottom of RVSM airspace?`, back: `FL290` },
      { front : `What is the max altitude with 1 AC PACK inop?`, back: `FL250` },
      { front : `What is the bottom of the High Altitude Chart?`, back: `FL180` },
      { front : `What flight level do you set an altimeter to standard?`, back: `FL180` },
      { front : `What altitude must a B737-800 decend to if pressure is lost and how fast?`, back: `14000 MSL in 4 minutes` },
      { front : `What is the top of Class G Airspace?`, back: `14500 MSL, 1200 AGL, 700 AGL` },
      { front : `With both AC PACK inop, what is the maximum authorized altitude?`, back: `10000 MSL` },
      { front : `What altitude is ADSB required? What mode?`, back: `10000 MSL. Mode C` },
      { front : `What is the maximum field elevation a B737-800 can take off from?`, back: `8400 MSL` },
      { front : `What is the top of a High Pressure Prognostic Chart?`, back: `FL600` },
      { front : `What is the top of a (GTG) Graphical Turbulence Guidance Chart?`, back: `FL500` },
      { front : `What is the top of a (FIP) Forecast Icing Product Chart?`, back: `FL300` },
      { front : `What flight level is a 200MB Chart?`, back: `FL390` },
      { front : `What flight level is a 300MB Chart?`, back: `FL300` },
      { front : `What flight level is a 400MB Chart?`, back: `FL240` },
      { front : `What flight level is a 500MB Chart?`, back: `FL180` },
      { front : `What flight level is a 700MB Chart?`, back: `10000 MSL` },
      { front : `What flight level is a 1000MB Chart?`, back: `Surface` },
      { front : `What is the bottom for a High Pressure Prognostic Chart?`, back: `FL250` },
      { front : `What is the top of a Low Level Prognostic Chart?`, back: `FL240` },
      { front : `What is the bottom of a (FIP) Forecast Icing Product Chart?`, back: `1000 MSL` },
      { front : `What is the bottom of a (GTG) Graphical Turbulence Guidance Chart?`, back: `1000 MSL` },
      { front : `What is the bottom of a Low Level Prognostic Chart?`, back: `Surface` },
      { front : `What is the bottom of a Surface Analysis Chart?`, back: `Surface` },
      { front : `What is the altitude is a (TAF) Terminal Aerodrome Forecast?`, back: `Surface` },
      { front : `What is the altitude is a (METAR) Meteorological Terminal Aerodrome Report?`, back: `Surface` },
];
