// flashcards/needtoknow.js
export const needtoknow = [
	{ front : "<b>What is the pilot-in-command solely responsible for under 121.533?", back: "Safety of: The Crew, Cargo, Passengers & Aircraft" },
	{ front : "<b>What is the dispatcher solely responsible for under 121.533?", back: "<ul><li><b>Monitoring</b> the progress of the flight</li><li>Issuing information to the PIC for the <b>Safety</b> of the flight</li><li><b>Canceling or Re-dispatching</b> a flight, if the DX or PIC determine the flight cannot operate or continue to operate safely as planned</li></ul>" },
	{ front : "<b>High Minimum Captain: What do you do to plate minimums at the departure and destination airports?", back: "Add 100' DA/HAT and 1/2SM" },
	{ front : "<b>What are standard alternate minimums for a non-precision approach?", back: "800'-2SM" },
	{ front : "<b>What 3 documents are required to be onboard a flight before it can legally depart?", back: "<ul><li>Dispatch Release</li><li>Load Manifest</li><li>Flight Plan</li></ul>" },
	{ front : "<b>When is a Drift-down Alternate required?", back: "When you can no longer maintain Method 1, so you revert to Method 2" },
	{ front : "<b>What is Method 1?", back: "At the point of engine failure, you drift down and maintain 1000’ clearance over critical obstacles<br>(Mostly Mountain Peaks)" },
	{ front : "<b>What is Method 2?", back: "At the point of engine failure, you drift down clearing a critical obstacle by 1000’ and drift down into a valley requiring a drift down alternate" },
	{ front : "<b>What are the 4 types of airports that can be found in an airlines Ops Spec?", back: "<b>R</b>egular, <b>R</b>efueling, <b>A</b>lternate, <b>P</b>rovisional<br><b>(RRAP)</b>" },
	{ front : "<b>When converting from MAGNETIC to TRUE, do you add or subtract an EAST variation?", back: "Add" },
	{ front : "<b>When converting from MAGNETIC to TRUE, do you add or subtract an WEST variation?", back: "Subtract" },
	{ front : "<b>When converting from TRUE to MAGNETIC, do you add or subtract an EAST variation?", back: "Subtract" },
	{ front : "<b>When converting from TRUE to MAGNETIC, do you add or subtract an WEST variation?", back: "Add" },
	{ front : "<b>When is a takeoff/departure alternate required?", back: "When the weather is below plate minimums at the departure airport." },
	{ front : "<b>What is a Provisional Airport?", back: "An airport that is near an airlines regular airport, in the event that the regular airport becomes temporarily unavailable, the airline can use this airport to continue serving the community" },
	{ front : "<b>What do you do in the event of loss communication between the flightcrew and dispatcher?", back: "Everything possible to re-establish communications before declaring an emergency" },
	{ front : "<b>What is the 1-2-3 Rule?", back: "<ul><li>+ or - <b>1</b> hour of the ETA</li><li><b>2000' ceiling</b></li><li><b>3 SM Visibility</b></li></ul><p>If at any point, <b>1</b> hour before the ETA or <b>1</b> hour after the ETA the ceiling is forecasted to be below <b>2</b>000', <b>OR</b> the visibility is forecasted to be below <b>3</b> SM, a destination alternate is <b>required</b> to be listed</p>" },
	{ front : "<b>What is a refueling airport?", back: "An Airport that an airline uses only for refueling purposes<br>(gas and go!)" },
	{ front : "<b>What must a dispatcher consider when computing a flight's minimum fuel supply?<br>121.647", back: "<ul><li>Weather (Wind or forecasted conditions)</li><li>Traffic Delays (Taxi & Landing)</li><li>Missed approaches</li><li>Any other conditions that may delay landing of the aircraft</li></ul>" },
	{ front : "<b>What is Operational Control?", back: "Exercising the authority to <b>Initiate</b>, <b>Conduct</b>, or <b>Terminate</b> a flight" },
	{ front : "<b>Are ATIS winds true or magnetic?", back: "Magnetic" },
	{ front : "<b>What is a regular Airport?", back: "An Airport that an airline uses as a regularly scheduled destination" },
	{ front : "<b>What are the 4 stages of a jet engine?", back: "Intake -> Compression -> Combustion -> Exhaust<br>(SUCK -> SQUEEZE -> BANG -> BLOW)" },
	{ front : "<b>What is a FDC NOTAM?", back: "<b>F</b>light <b>D</b>ata <b>C</b>enter <b>Not</b>ice to <b>A</b>ir<b>m</b>en<br>Identifies changes to published charts and/or procedures" },
	{ front : "<b>What is a D NOTAM?", back: "<b>D</b>istant <b>Not</b>ice to <b>A</b>ir<b>m</b>en<br>it identifies physical items located at the issuing airport, ex: closed runways/taxiways, inoperative NAVAIDs, field lighting conditions, etc" },
	{ front : "<b>What is a suitable airport?", back: "An adequate airport where the weather is at or above plate minimums for landing" },
	{ front : "<b>What is an adequate airport?", back: "An airport that has everything an airline requires to operate in and out of<br>(runways/taxiways, fuel, ground service equipment, etc)" },
	{ front : "<b>What is a supplemental operation?", back: "Any unscheduled flight, or between a city pair that is operated fewer than 5 times per week" },
	{ front : "<b>What information must be included in the dispatch release?<br>121.687", back: "<b>FATWIVES</b><ul><li>Fuel</li><li>Airports (departure/origin, destination, alternates, intermediate)</li><li>Trip#/Tail#</li><li>Weather Package</li><li>IFR flight plan</li><li>VFR flight plan</li><li>ETOPs/ETP</li><li>Signatures (DX & PIC)</li></ul>" },
	{ front : "<b>What is a High Minimum Captain?", back: "A captain with less than 100 hours in an aircraft type" },
	{ front : "<b>What is an alternate airport?", back: "An airport which is specified on a flight plan, to which a flight may proceed to if the destination becomes inadvisable." },
	{ front : "<b>What are flag fuel requirements?", back: "<ul><li>Trip fuel to destination</li><li>Plus 10% of the trip fuel</li><li>Fuel to the furthest alternate</li><li>Reserves of 30 minutes at holding speed, at 1500' AGL</li></ul>" },
	{ front : "<b>What are domestic fuel requirements?", back: "<ul><li>Trip fuel to destination</li><li>Fuel to the furthest alternate</li><li>Reserves of 45 minutes at normal cruise speed</li></ul>" },
	{ front : "<b>How long can a flag operation be on the ground without requiring a new release?", back: "No more than 6 hours" },
	{ front : "<b>How long can a domestic operation be on the ground without requiring a new release?", back: "No more than 1 hour" },
	{ front : "<b>Are METAR/TAF winds true or magnetic?", back: "True" },
	{ front : "<b>What is joint responsibility and who shares it?<br>121.533", back: "The pilot in command and the aircraft dispatcher are jointly responsible (50/50) for: <ul><li>Preflight planning</li><li>Delay of the flight</li><li>Dispatch Release</li></ul>" },
	{ front : "<b>What is a flag operation?", back: "A flight from the US to outside of the 48 contiguous states<br>If a flight is coming to the 48 contiguous, it will be treated as a domestic flight" },
	{ front : "<b>What is a domestic operation?", back: "A flight within the continental 48 contiguous states" },
	{ front : "<b>What do  you do to the plate minimums for a High Minimum Captain at any alternate airport?", back: "No less than 300'-1" },
];