// flashcards/theatmosphere.js
export const theatmosphere = [
	{ front : `What does temperature do in the Troposphere?`, back: `Temperature decreases with altitude` },
	{ front : `What does all of earths weather occur?`, back: `In the Troposphere` },
	{ front : `What does temperature do in the Stratosphere?`, back: `Temperature increases with altitude` },
	{ front : `What is the tropopause?`, back: `A boundary layer between the troposphere and the stratosphere` },
	{ front : `What does ISA mean?`, back: `<p><b>I</b>nternational <b>S</b>tandard <b>A</b>tmosphere</p>` },
	{ front : `ISA<br>What is the SLP?`, back: `<p>Sea Level Pressure: 29.92hg / 1013.2mb</p>` },
	{ front : `ISA<br>What is the Lapse Rate?`, back: `<p>Lapse Rate: -2°c/1000' Climbed</p>` },	
	{ front : `ISA<br>What is the Temperature?`, back: `<p>Temerature: +15°c (59°f)</p>` },
	{ front : `What is an air mass?`, back: `A parcel of air with uniform characteristics` },
	{ front : `Describe the characteristics of a Cold Front`, back: `<ul><li>Fast Moving</li><li>Cumulous Clouds</li><li>Turbulent Air</li><li>Showery Precipitation</li><li>Good Surface Visibility</li><li>Cold Dense Air, Lots of Lift</li></ul>`},
	{ front : `Describe the characteristics of a Warm Front`, back: `<ul><li>Slow Moving</li><li>Stratus Clouds</li><li>Smooth Air</li><li>Steady Precipitation</li><li>Bad Surface Visibility</li><li>Warm Less Dense Air, Lack of Lift</li></ul>`},
	{ front : `Describe the characteristics of a Stationary Front`, back: `<ul><li>Barely Moving</li><li>Winds Blowing Parelle across the front</li><li>Similar Conditions to a Cold Front</li></ul>` },
	{ front : `Describe the characteristics of an Occluded Front`, back: `<ul><li>Cold Air catches up to a warm front</li><li>Cuts a warm front off with another Cold Front</li><li>Slow Moving</li><li>Similar to a Cold Front</li></ul>` },
	{ front : `Describe the characteristics of a Dry Front`, back: `<ul><li>Separation of most and dry air</li><li>Sharp/Rapid changes in Dew Point</li><li>Can lead to thunderstorms</li></ul>` },
	{ front : `Describe a Trough?`, back: `Elongated line of Low Pressure` },
	{ front : `Describe a Ridge?`, back: `Elongated line of High Pressure` },
	{ front : `Describe a Squall Line?`, back: `Line of Thunderstorms<br>Typically found ahead of Cold Fronts` },
	{ front : `Describe a Squall?`, back: `Wall of wind, 15mph or more` },
];