// flashcards/wxproductsnoimages.js
export const wxproductsnoimages = [
	{ front: "What information does a Winds/Temps Aloft chart provide?", back: "<ul><li>Wind Direction</li><li>Wind Speed</li><li>Air Temperature (Celsius)</li>(At various altitudes)</ul>" },
	{ front: "How often are Radar Summaries issued?", back: "Every 30 mins; at :15 and :45" },
	{ front: "Which weather product are temperatures and dew points given in Fahrenheit?", back: "Only the Surface Analysis Chart" },
	{ front: "What flight level is a 200MB constant pressure chart?", back: "FL390" },
	{ front: "What flight level is a 300MB constant pressure chart?", back: "FL300" },
	{ front: "What flight level is a 400MB constant pressure chart?", back: "FL240" },
	{ front: "What flight level is a 500MB constant pressure chart?", back: "FL180" },
	{ front: "What altitude is a 700MB constant pressure chart?", back: "10,000' MSL" },
	{ front: "What altitude is a 1000MB constant pressure chart?", back: "1000' MSL" },
	{ front: "What types of weather does a Convective SIGMET cover?", back: "<ul><li>Embedded Thunderstorms</li><li>Severe Thunderstorms</li><li>Squall Lines</li></ul>" },
	{ front: "What are the forecasted altitudes on a High-Level-Prognostic chart?", back: "FL250 to FL600" },
	{ front: "How many types of AIRMETs are there? What are the names?", back: "<p><b>3:</b></p><ul><li><b>S</b>ierra</li><li><b>T</b>ango</li><li><b>Z</b>ulu</li></ul>" },
	{ front: "What information does a Radar Summary provide?", back: "<ul><li>Precipitation location and intensity</li><li>Cell tops and movement</li></ul>" },
	{ front: "How many observations are there? What are they?", back: "<p><b>4:</b></p><ul><li>METAR</li><li>PIREP</li><li>Radar Summary</li><li>Surface Analysis Chart</li></ul><p>(Easiest way to remember how many forecast and how many observations is to remember the 4 observations)</p>" },
	{ front: "Surface Analysis Chart: Observation or Forecast?", back: "Observation" },
	{ front: "How long is a Radar Summary valid?", back: "Valid only at the moment observed" },
	{ front: "How long is a METAR valid?", back: "Valid only at the moment observed" },
	{ front: "How long is a High-Level-Prognostic chart valid?", back: "Valid at forecast time" },
	{ front: "How much area is covered by a SIGMET?", back: "Greater than 3,000 Square Miles" },
	{ front: "What 6 pieces of information does a High-Level Prognostic chart provide?", back: "<ul><li>Jet stream location/speeds</li><li>Tropopause heights (as flight levels)</li><li>Convective activity</li><li>Turbulence (moderate and greater)</li><li>Volcanic activity</li><li>Tropical cyclones (tropical storms, hurricanes, typhoons)</li></ul>" },
	{ front: "What 8 observed conditions can a PIREP cover?", back: "<ul><li>Turbulence</li><li>Wind Shear</li><li>Icing</li><li>Convective activity</li><li>Visibility</li><li>Precipitation</li><li>Runway braking action</li><li>Cloud height and thickness</li></ul>" },
	{ front: "What 3 pieces of information does a Constant Pressure Analysis chart provide?", back: "<ul><li>Isotachs</li><li>Height contour lines</li><li>Wind speeds</li></ul>" },
	{ front: "AIRMET: Observation or Forecast?", back: "Forecast" },
	{ front: "How often are AIRMETs issued?", back: "Every 6 hours, or 4 times a day" },
	{ front: "How often are High-Level Prognostic charts issued?", back: "Every 6 hours, or 4 times a day" },
	{ front: "How long is a Winds/Temps Aloft chart valid?", back: "24 Hours" },
	{ front: "How often are TAFs issued?", back: "Every 6 hours, or 4 times a day" },
	{ front: "How often are Constant Pressure Analysis Charts issued?", back: "Every 6 hours, or 4 times a day" },
	{ front: "What is a SIGMET?", back: "The same as an AIRMET, but for severe turbulence, icing, or IMC (Instrument Meteorological Conditions)" },
	{ front: "How often are PIREPs issued?", back: "As needed (Pilot observations)" },
	{ front: "What would a jagged orange line indicate on a Surface Analysis Chart?", back: "A ridge" },
	{ front: "Radar Summary: Observation or Forecast?", back: "Observation" },
	{ front: "What information does an AIRMET Sierra provide?", back: "IMC (Instrument Meteorological Conditions)" },
	{ front: "What information does an AIRMET Tango provide?", back: "Turbulence" },
	{ front: "What information does an AIRMET Zulu provide?", back: "Icing" },
	{ front: "High-Level Prognostic Chart: Observation or Forecast?", back: "Forecast" },
	{ front: "How long is a Volcanic Ash SIGMET valid for?", back: "6 hours" },
	{ front: "How often are Convective SIGMETs issued?", back: "Every 2 hours (or as needed)" },
	{ front: "How long is an AIRMET valid for?", back: "6 hours" },
	{ front: "How long is a Constant Pressure Analysis Chart valid for?", back: "Valid only at forecast time" },
	{ front: "PIREP: Observation or Forecast?", back: "Observation" },
	{ front: "Winds/Temps Aloft Chart: Observation or Forecast?", back: "Forecast" },
	{ front: "How long is a TAF valid for?", back: "Typically 24 Hours" },
	{ front: "How long is a Convective SIGMET valid for?", back: "2 hours" },
	{ front: "METAR: Observation or Forecast?", back: "Observation" },
	{ front: "How long is a SIGMET valid for?", back: "4 hours" },
	{ front: "How long is a PIREP valid for?", back: "Valid only at the moment observed" },
	{ front: "How often are SIGMETs issued?", back: "Every 4 hours (or as needed)" },
	{ front: "How long is a Surface Analysis Chart valid for?", back: "Valid only at the moment observed" },
	{ front: "TAF: Observation or Forecast?", back: "Forecast" },
	{ front: "How often are Surface Analysis Charts issued?<b>", back: "Every 3 hours, beginning at 0000z" },
	{ front: "How often are Volcanic Ash SIGMETs issued?", back: "Every 4 hours" },
	{ front: "Constant Pressure Analysis Chart: Observation or Forecast?", back: "Forecast" },
	{ front: "How often are METARs issued?", back: "Hourly" },
	{ front: "How often are Winds/Temps Aloft charts issued?", back: "Every 6 hours, or 4 times daily" },
	{ front: "What 8 pieces of information does a Surface Analysis Chart cover?", back: "<ul><li>Fronts</li><li>High & Low Pressure areas</li><li>Isobars</li><li>Ridges and Troughs</li><li>Temperatures</li><li>Dew points</li><li>Wind speed and direction</li><li>Sea-level pressure</li></ul>" },
];